In [2]:
import json
import requests
import numpy as np
#from IPython.display import HTML
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
state = input("Which State to gather data from?(Abbreviations only) ")
response = requests.get("http://find-us.herokuapp.com/US")
persons = json.loads(response.text)
print(query_url)

Which State to gather data from?(Abbreviations only) california
http://find-us.herokuapp.com/US/california

In [39]:
response_temp_json = json.loads(response_temp.text)
#print(json.dumps(response_temp_json, sort_keys=True, indent=4, separators=(',', ': ')))

In [43]:
for i in range(int(response_temp_json['totalPages'])):
    query_url_loop = "http://www.missingkids.com/missingkids/servlet/JSONDataServlet?action=publicSearch&searchLang=en_US&goToPage={}".format(i+1)
    response_loop = session.get(query_url_loop)
    response_loop_json = json.loads(response_loop.text)
    #print("starting loop " + str(i+1))
    #print(query_url_loop)
    for ii in range(len(response_loop_json['persons'])):
        person_name = response_loop_json['persons'][ii]['firstName'] + " " + response_loop_json['persons'][ii]['lastName']
        if response_loop_json['persons'][ii]['middleName'] != "":
            person_name.replace("", " {} ".format(response_loop_json['persons'][ii]['middleName']))
        
        index_num = (len(response_loop_json['persons']) * i) + ii
        try:
            df.set_value(index_num,'name',person_name)
            df.set_value(index_num,'age',response_loop_json['persons'][ii]['age'])
            df.set_value(index_num,'missing_date',response_loop_json['persons'][ii]['missingDate'])
            df.set_value(index_num,'missing_city',response_loop_json['persons'][ii]['missingCity'])
            df.set_value(index_num,'missing_county',response_loop_json['persons'][ii]['missingCounty'])
            df.set_value(index_num,'missing_state',response_loop_json['persons'][ii]['missingState'])
        except:
            print('error T.T')
            continue
        #print(person_name)
            
df.to_csv("NCMEC_{}.csv".format(state), encoding="utf-8", index=False)

error T.T

,age,missing_date,missing_city,missing_county,missing_state
name,,,,,
ABIGAIL SMITH,1,1,1,1,1
ACACIA DUVALL,1,1,1,1,1
ADALBERTO ZAMORA,1,1,1,1,1
ADINDA CURRY,1,1,1,1,1
ADRIANA PATTON,1,1,1,1,1
ADRIANA ROJAS,1,1,1,1,1
AJAH MCCOY,1,1,1,1,1
ALAEJAH WATSON,1,1,1,1,1
ALDEBARAN ROMERO,1,1,1,1,1
ALEJANDRA RIVERA-ROMERO,1,1,1,1,1
ALEJANDRA SCIORTINO,1,1,1,1,1
ALEX ALFREDO BERNAL VARGAS,1,1,1,1,1
ALEX ORTEGA,1,1,1,1,1
ALEXANDER OLIVE,1,1,1,1,1
ALEXANDER RIFFENBURG,1,1,1,1,1
ALEXANDRA MCINTIRE,1,1,1,1,1
ALEXANDRIA MENDOZA,1,1,1,1,1
ALEXIS GIBBONS,1,1,1,1,1
ALEXIS HERNANDEZ,1,1,1,1,1
ALEXSIA VANEGAS,1,1,1,1,1
ALFONSO VENEGAS,1,1,1,1,1
ALINA CASEY TORRES,1,1,1,1,1
ALISEZAH GREEN,1,1,1,1,1
ALLISON PAPION,1,1,1,1,1
ALMA ROOT,1,1,1,1,1
ALONSO RUIZ,1,1,1,1,1
AMANDA CAMPBELL,1,1,1,1,1
AMANDA CROSS,1,1,1,1,1
AMANDA RIVERA,1,1,1,1,1
AMBER SWARTZ,1,1,1,1,1
...,...,...,...,...,...
TRACY DAVENPORT,1,1,1,1,1
TRAVIS ZWIEG,1,1,1,1,1
TYERRA TOWNSEND,1,1,1,1,1
UNKNOWN DOE1986,1,1,1,1,1
VALERIA VENTURA,1,1,1,1,1
VERONICA COLLINS,1,1,1,1,1
VERONICA MARTINEZ,1,1,1,1,1
VICTOR JIMENEZ CINTILLO,1,1,1,1,1
VICTOR RAMIREZ,1,1,1,1,1
VICTORIA ESCALANTE,1,1,1,1,1
VIOLET MATORY,1,1,1,1,1
VIRGINIA HURTADO,1,1,1,1,1
WALTER LEO,1,1,1,1,1
WAYNE SAWYER,1,1,1,1,1
WESLEY RIVERA-ROMERO,1,1,1,1,1
WHITNEY ELLISEAU,1,1,1,1,1
WILLIAM CORDES,1,1,1,1,1
XAVIER LOGAN,1,1,1,1,1
XAVIER MOHAMMAD,1,1,1,1,1
XIMENA GRANADOS,1,1,1,1,1
YADIRA ESPINOZA,1,1,1,1,1
YAJAIRA MATEO CRUZ,1,1,1,1,1
YAMILEX MARES,1,1,1,1,1
YANELY GUZMAN,1,1,1,1,1
YASHASWI KULSHRESHTHA,1,1,1,1,1
YECHEZKEL LESSERSON,1,1,1,1,1
YEKUSIEL LESSERSON,1,1,1,1,1
YOCHABEL GARCIA,1,1,1,1,1
YOLANDA WILLIAMS,1,1,1,1,1
ZHI YING ZHEN,1,1,1,1,1